import React from 'react';
import { ArrowRight, Check } from 'lucide-react';
import { useNavigation } from '../context/NavigationContext';
import { FeeCalculator } from '../components/FeeCalculator';
import { NetworkIllustration } from '../components/NetworkIllustration';

export const BusinessPage: React.FC = () => {
  const { navigateTo } = useNavigation();
  const features = ['Accept customer payments on your website, app or online store', 'Simple integration with test mode', 'View all past transactions', 'Payment links and invoices', 'Clear fees per sale', 'Verified businesses only'];
  return <div className="mx-auto max-w-7xl px-4 pt-28 pb-20 sm:px-6 lg:px-8"><section className="signature-intro relative overflow-hidden"><NetworkIllustration /><div className="relative z-10 max-w-3xl"><span className="text-xs font-black uppercase tracking-widest text-[#2F6FF0]">GlobalPay Business</span><h1 className="mt-4 text-4xl font-black text-slate-900 dark:text-white sm:text-6xl">Accept payments from your customers.</h1><p className="mt-5 text-lg text-slate-600 dark:text-slate-300">Add GlobalPay to your website, app, or online store and manage your payment records.</p></div></section><div className="mt-14 grid items-start gap-10 lg:grid-cols-2"><div><h2 className="text-2xl font-black text-slate-900 dark:text-white">What you can do</h2><ul className="mt-6 space-y-4">{features.map((item) => <li key={item} className="flex gap-3 text-slate-700 dark:text-slate-200"><Check className="h-5 w-5 shrink-0 text-emerald-500" />{item}</li>)}</ul><div className="mt-8 rounded-2xl border border-slate-200 bg-slate-50 p-5 text-sm font-bold text-slate-700 dark:border-slate-800 dark:bg-[#07132B] dark:text-slate-200">Accepting crypto payments: coming soon</div><h2 className="mt-10 text-2xl font-black text-slate-900 dark:text-white">Simple integration</h2><p className="mt-4 text-sm leading-relaxed text-slate-600 dark:text-slate-300">Test your store or app first. Continue after your business is verified. Simple documentation will help you get started.</p><h2 className="mt-10 text-2xl font-black text-slate-900 dark:text-white">Verification</h2><p className="mt-4 text-sm leading-relaxed text-slate-600 dark:text-slate-300">Business accounts complete business verification before launch.</p><button onClick={() => navigateTo('business-signup')} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-[#0052FF] to-[#00D2B4] px-6 py-3 font-bold text-white">Create a Business account <ArrowRight className="h-4 w-4" /></button></div><FeeCalculator route="business" /></div></div>;
};
