import React, { useState } from 'react';
import { ArrowRight, Check, RefreshCw } from 'lucide-react';
import { useNavigation } from '../context/NavigationContext';

const currencies = ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'BTC', 'ETH'];

export const TransferEstimator: React.FC = () => {
  const [amount, setAmount] = useState('250');
  const [from, setFrom] = useState('USD');
  const [to, setTo] = useState('EUR');
  const estimated = (Number(amount) || 0) * 0.92;
  return <div className="bg-white dark:bg-[#07132B] rounded-3xl p-6 border border-slate-200 dark:border-slate-800 shadow-xl">
    <div className="flex items-center justify-between mb-5"><h2 className="text-xl font-black text-slate-900 dark:text-white">Estimate your transfer</h2><span className="text-xs font-bold text-emerald-600 dark:text-emerald-400">Fee: less than 3%</span></div>
    <label className="block text-xs font-bold text-slate-500 mb-2">You send</label>
    <div className="flex gap-2 mb-4"><input value={amount} onChange={(event) => setAmount(event.target.value)} type="number" min="0" className="min-w-0 flex-1 px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 font-bold text-slate-900 dark:text-white" /><select value={from} onChange={(event) => setFrom(event.target.value)} className="px-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 font-bold text-slate-900 dark:text-white">{currencies.map((currency) => <option key={currency}>{currency}</option>)}</select></div>
    <div className="flex items-center gap-3 my-3 text-xs text-slate-500"><span className="h-px flex-1 bg-slate-200 dark:bg-slate-700" /><RefreshCw className="w-4 h-4" /><span className="h-px flex-1 bg-slate-200 dark:bg-slate-700" /></div>
    <label className="block text-xs font-bold text-slate-500 mb-2">Recipient receives (estimate)</label>
    <div className="flex gap-2"><div className="min-w-0 flex-1 px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 font-bold text-slate-900 dark:text-white">{estimated.toFixed(2)}</div><select value={to} onChange={(event) => setTo(event.target.value)} className="px-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 font-bold text-slate-900 dark:text-white">{currencies.map((currency) => <option key={currency}>{currency}</option>)}</select></div>
    <p className="mt-4 text-xs leading-relaxed text-slate-500">Estimate only. Final amount is confirmed before you pay.</p>
  </div>;
};

const ProductCard: React.FC<{ title: string; text: string; items: string[]; onClick: () => void }> = ({ title, text, items, onClick }) => <div className="p-7 rounded-3xl bg-white dark:bg-[#07132B] border border-slate-200 dark:border-slate-800 shadow-lg flex flex-col"><h2 className="text-2xl font-black text-slate-900 dark:text-white">{title}</h2><p className="mt-3 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{text}</p><ul className="mt-5 space-y-3 text-sm text-slate-700 dark:text-slate-200 flex-1">{items.map((item) => <li key={item} className="flex gap-2"><Check className="w-4 h-4 mt-0.5 text-emerald-500 shrink-0" />{item}</li>)}</ul><button onClick={onClick} className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#0052FF] dark:text-cyan-400">Learn more <ArrowRight className="w-4 h-4" /></button></div>;

export const HomePage: React.FC = () => {
  const { navigateTo } = useNavigation();
  return <div className="pt-28 pb-20"><section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-12 items-center"><div><span className="text-xs font-black uppercase tracking-widest text-[#0052FF] dark:text-cyan-400">GlobalPay</span><h1 className="mt-4 text-4xl sm:text-6xl font-black leading-tight text-slate-900 dark:text-white">Send and receive payments in many currencies.</h1><p className="mt-5 text-lg leading-relaxed text-slate-600 dark:text-slate-300">GlobalPay helps people and businesses send and receive local, international, and crypto payments through trusted payment partners.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={() => navigateTo('get-started')} className="px-6 py-3 rounded-xl font-bold text-white bg-gradient-to-r from-[#0052FF] to-[#00D2B4]">Get Started <ArrowRight className="inline w-4 h-4 ml-1" /></button><button onClick={() => navigateTo('how-it-works')} className="px-6 py-3 rounded-xl font-bold text-slate-800 dark:text-white border border-slate-300 dark:border-slate-700">How it works</button></div><div className="mt-6 flex flex-wrap gap-5 text-xs font-bold text-slate-500"><span>Verified accounts only</span><span>Less than 3% per transaction</span></div></div><TransferEstimator /></section><section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-20"><h2 className="text-3xl font-black text-slate-900 dark:text-white text-center">Choose the account that fits you</h2><div className="grid md:grid-cols-2 gap-6 mt-8"><ProductCard title="For Personal" text="For individuals who need to send and receive payments across currencies." items={['Send and receive local and international payments', 'Use multiple currencies, including crypto', 'See your payment history']} onClick={() => navigateTo('personal')} /><ProductCard title="For Business" text="For merchants who want to accept payments on a website, app, or online store." items={['Accept customer payments', 'View past transactions', 'Create payment links']} onClick={() => navigateTo('business')} /></div></section><section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 mt-20"><h2 className="text-3xl font-black text-slate-900 dark:text-white text-center">How it works</h2><div className="grid md:grid-cols-3 gap-4 mt-8">{['Create your account', 'Verify your identity', 'Send or receive payments'].map((step, index) => <div key={step} className="p-5 rounded-2xl bg-slate-50 dark:bg-[#07132B] border border-slate-200 dark:border-slate-800"><span className="text-sm font-black text-[#0052FF]">0{index + 1}</span><p className="mt-3 font-bold text-slate-900 dark:text-white">{step}</p></div>)}</div></section></div>;
};
