import React from 'react';
import { ArrowRight, Check } from 'lucide-react';
import { useNavigation } from '../context/NavigationContext';
import { FeeCalculator } from '../components/FeeCalculator';

export const PersonalPage: React.FC = () => {
  const { navigateTo } = useNavigation();
  const features = ['Send and receive local payments', 'Send money abroad in many currencies', 'Send and receive crypto', 'Clear fee shown before you pay', 'Payment history', 'Verified accounts only'];
  return <div className="mx-auto max-w-7xl px-4 pt-28 pb-20 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-xs font-black uppercase tracking-widest text-[#0052FF] dark:text-cyan-400">GlobalPay Personal</span><h1 className="mt-4 text-4xl font-black text-slate-900 dark:text-white sm:text-6xl">Payments for your everyday life.</h1><p className="mt-5 text-lg text-slate-600 dark:text-slate-300">Send and receive local and international payments in multiple currencies. Buy, sell, swap, send and receive crypto.</p></div><div className="mt-14 grid items-start gap-10 lg:grid-cols-2"><div><h2 className="text-2xl font-black text-slate-900 dark:text-white">What you can do</h2><ul className="mt-6 space-y-4">{features.map((item) => <li key={item} className="flex gap-3 text-slate-700 dark:text-slate-200"><Check className="h-5 w-5 shrink-0 text-emerald-500" />{item}</li>)}</ul><div className="mt-8 rounded-2xl border border-slate-200 bg-slate-50 p-5 text-sm leading-relaxed text-slate-600 dark:border-slate-800 dark:bg-[#07132B] dark:text-slate-300">GlobalPay does not hold your funds. Payments are processed directly by our licensed payment partners, and every account must be verified before sending or receiving money.</div><p className="mt-8 text-sm leading-relaxed text-slate-600 dark:text-slate-300">Crypto prices can go up and down. You can lose money. Crypto services depend on verification and availability. Crypto services are provided through registered third-party partners in line with applicable regulations.</p><h2 className="mt-10 text-2xl font-black text-slate-900 dark:text-white">Verification</h2><p className="mt-4 text-sm leading-relaxed text-slate-600 dark:text-slate-300">Everyone must complete identity verification before using the service.</p><button onClick={() => navigateTo('personal-signup')} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-[#0052FF] to-[#00D2B4] px-6 py-3 font-bold text-white">Create a Personal account <ArrowRight className="h-4 w-4" /></button></div><FeeCalculator /></div></div>;
};
