import React from 'react';
import { ArrowRight, Check } from 'lucide-react';
import { useNavigation } from '../context/NavigationContext';
import { TransferEstimator } from './HomePage';

export const PersonalPage: React.FC = () => {
  const { navigateTo } = useNavigation();
  return <div className="pt-28 pb-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-xs font-black uppercase tracking-widest text-[#0052FF] dark:text-cyan-400">GlobalPay Personal</span><h1 className="mt-4 text-4xl sm:text-6xl font-black text-slate-900 dark:text-white">Payments for your everyday life.</h1><p className="mt-5 text-lg text-slate-600 dark:text-slate-300">Send and receive local and international payments in multiple currencies, including crypto.</p></div><div className="grid lg:grid-cols-2 gap-10 mt-14 items-start"><div><h2 className="text-2xl font-black text-slate-900 dark:text-white">What you can do</h2><ul className="mt-6 space-y-4">{['Send and receive local and international payments', 'Use multiple currencies', 'Send and receive crypto', 'See your payment history'].map((item) => <li key={item} className="flex gap-3 text-slate-700 dark:text-slate-200"><Check className="w-5 h-5 text-emerald-500 shrink-0" />{item}</li>)}</ul><div className="mt-8 p-5 rounded-2xl bg-slate-50 dark:bg-[#07132B] border border-slate-200 dark:border-slate-800 text-sm leading-relaxed text-slate-600 dark:text-slate-300">GlobalPay does not keep your money. We connect you to trusted payment partners that move the money and we record each transaction.</div><h2 className="text-2xl font-black text-slate-900 dark:text-white mt-10">Three steps</h2><ol className="mt-5 space-y-3 text-sm text-slate-600 dark:text-slate-300"><li><b>1.</b> Sign up for a Personal account.</li><li><b>2.</b> Verify your identity with an ID and selfie.</li><li><b>3.</b> Start sending or receiving payments.</li></ol><button onClick={() => navigateTo('personal-signup')} className="mt-8 px-6 py-3 rounded-xl font-bold text-white bg-gradient-to-r from-[#0052FF] to-[#00D2B4]">Create a Personal account <ArrowRight className="inline w-4 h-4 ml-1" /></button></div><TransferEstimator /></div></div>;
};
