import React from 'react';
import { Check } from 'lucide-react';

const SignupPage: React.FC<{ business: boolean }> = ({ business }) => { const title = business ? 'Create a Business account' : 'Create a Personal account'; const needs = business ? ['Company registration documents', 'Director details', 'Bank details'] : ['ID document', 'Selfie', 'Proof of address if required']; return <div className="pt-28 pb-20 max-w-3xl mx-auto px-4 sm:px-6 lg:px-8"><div className="p-8 sm:p-12 rounded-3xl bg-white dark:bg-[#07132B] border border-slate-200 dark:border-slate-800 shadow-lg"><span className="text-xs font-black uppercase tracking-widest text-[#0052FF] dark:text-cyan-400">Signup</span><h1 className="mt-4 text-4xl font-black text-slate-900 dark:text-white">{title}</h1><p className="mt-4 text-slate-600 dark:text-slate-300">This page shows the account setup steps. Verification is not connected yet.</p><h2 className="mt-10 text-xl font-black text-slate-900 dark:text-white">What you will need</h2><ul className="mt-5 space-y-4">{needs.map((item) => <li key={item} className="flex gap-3 text-slate-700 dark:text-slate-200"><Check className="w-5 h-5 text-emerald-500" />{item}</li>)}</ul><div className="mt-10 p-4 rounded-xl bg-slate-50 dark:bg-slate-900 text-sm text-slate-600 dark:text-slate-300">Complete the form and verification steps here once the account flow is ready.</div><button className="mt-8 w-full py-3 rounded-xl font-bold text-white bg-gradient-to-r from-[#0052FF] to-[#00D2B4]">Continue</button></div></div>; };
export const PersonalSignupPage: React.FC = () => <SignupPage business={false} />;
export const BusinessSignupPage: React.FC = () => <SignupPage business />;
const SigninPage: React.FC<{ business: boolean }> = ({ business }) => <div className="pt-28 pb-20 max-w-lg mx-auto px-4 sm:px-6 lg:px-8"><div className="p-8 rounded-3xl bg-white dark:bg-[#07132B] border border-slate-200 dark:border-slate-800 shadow-lg"><h1 className="text-3xl font-black text-slate-900 dark:text-white">Sign in to your {business ? 'Business' : 'Personal'} account</h1><p className="mt-4 text-sm text-slate-600 dark:text-slate-300">Enter your email and password to continue.</p><label className="block mt-8 text-xs font-bold text-slate-600 dark:text-slate-300">Email<input type="email" className="mt-2 w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700" /></label><label className="block mt-4 text-xs font-bold text-slate-600 dark:text-slate-300">Password<input type="password" className="mt-2 w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700" /></label><button className="mt-7 w-full py-3 rounded-xl font-bold text-white bg-gradient-to-r from-[#0052FF] to-[#00D2B4]">Sign In</button></div></div>;
export const PersonalSigninPage: React.FC = () => <SigninPage business={false} />;
export const BusinessSigninPage: React.FC = () => <SigninPage business />;
